name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Enable docker experimental
        run: |
          echo '{"experimental":true,"exec-opts":["native.cgroupdriver=cgroupfs"],"cgroup-parent":"/actions_job"}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build and push
        run: |
          now=$(date --utc +"%Y.%-m.%-d.%-H.%-M.%-S")
          python_img_name='ghcr.io/sa4zet-org/docker.img.python'
          docker build --squash --file python.dockerfile --tag="$python_img_name:$now" --tag="$python_img_name:latest" --build-arg="docker_img=$python_img_name" .
          docker push $python_img_name:$now
          docker push $python_img_name:latest
